#!/bin/bash

echo "╔════════════════════════════════════════════════════════════════╗"
echo "║           📱 iOS 用户注册流程测试准备                        ║"
echo "╚════════════════════════════════════════════════════════════════╝"
echo ""

# 检查 API 服务
echo "🔍 检查 API 服务状态..."
if lsof -Pi :3000 -sTCP:LISTEN -t >/dev/null ; then 
  echo "✅ API 服务正在运行在端口 3000"
else 
  echo "❌ API 服务未运行"
  echo ""
  echo "请先启动 API 服务："
  echo "   cd wanderlog_api && npm run dev"
  echo ""
  exit 1
fi

echo ""

# 清理测试用户
echo "🧹 清理之前的测试用户..."
cd "$(dirname "$0")/wanderlog_api"
npx tsx cleanup_test_user.ts

echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "✅ 准备就绪！现在可以开始 iOS 测试了"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "📱 步骤 1: 启动 iOS 应用"
echo "   cd wanderlog_app"
echo "   flutter run"
echo ""
echo "📝 步骤 2: 在应用中注册新用户"
echo "   Email:    blcubahaa0627@gmail.com"
echo "   Password: Test123456"
echo "   Name:     Test User (可选)"
echo ""
echo "📧 步骤 3: 获取验证码"
echo ""
echo "   方法 1: 检查邮箱"
echo "   ────────────────────────────"
echo "   打开邮箱 blcubahaa0627@gmail.com 查看验证邮件"
echo ""
echo "   方法 2: 使用 Prisma Studio"
echo "   ────────────────────────────"
echo "   cd wanderlog_api && npx prisma studio"
echo "   访问 http://localhost:5555"
echo "   查看 VerificationToken 表"
echo ""
echo "   方法 3: 命令行查询"
echo "   ────────────────────────────"
echo "   cd wanderlog_api"
echo "   npx tsx -e \""
echo "   import { PrismaClient } from '@prisma/client';"
echo "   const prisma = new PrismaClient();"
echo "   const token = await prisma.verificationToken.findFirst({"
echo "     where: { "
echo "       user: { email: 'blcubahaa0627@gmail.com' },"
echo "       type: 'EMAIL_VERIFICATION'"
echo "     },"
echo "     orderBy: { createdAt: 'desc' }"
echo "   });"
echo "   console.log('验证码:', token?.token);"
echo "   await prisma.\$disconnect();"
echo "   \""
echo ""
echo "✉️ 步骤 4: 在应用中输入验证码"
echo "   在 6 个输入框中输入验证码"
echo "   输入完成后会自动验证"
echo ""
echo "🎉 步骤 5: 验证成功"
echo "   应该自动跳转到主页"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "💡 提示："
echo "   - API 日志会实时显示注册和验证请求"
echo "   - 验证码有效期为 15 分钟"
echo "   - 可以点击 'Resend Code' 重新发送验证码"
echo ""
echo "📖 详细指南：IOS_REGISTRATION_TEST_GUIDE.md"
echo ""
